### ISSUE TITLE
Chrome: No background image

### ISSUE THREAD

**Issue by n-kb** [ctt-data/escape#3]
![screenshot from 2018-12-07 09-03-32](https://user-images.githubusercontent.com/864677/49635119-07f0d300-f9ff-11e8-9726-b9b89738729e.png)

Tested on Chrome 71 / Ubuntu 18.04

**Comment by oebat** [comment]
It is working on Chrome Version 70.0.3538.110 (64-Bit)

**Comment by n-kb** [comment]
@oebat If you wish, you can test on different browsers using https://testingbot.com/

**Comment by oebat** [comment]
DESKTOP
*Works* in:
Linux - Chrome 64

MacOS High Sierra - Chrome 69

Does *not work* in:
Internet Explorer (--> does not matter no one is using it anymore) 
or Edge (--> we do not care, no one we know is using it. Even our grandparents use Firefox or other.)

Windows 7 - IE9 


MOBILE:
Chrome on Android 7.1 - Nexus 7 --> Landscape Mode --> works!
--> vertical no image.

Safari on iOS 11.4  - iPhone 8 Plus --> works perfectly
